### PR TITLE
s/--current_week/--current-week in docs

### PR DESCRIPTION
**Pull request by mehlah**
🤗

### CODE REVIEW

**Comment by mehlah** [comment]
Looks like both syntaxes are working. Sorry :)

**Comment by paulRbr** [comment]
I was going to say, are you sure: https://github.com/trainline-eu/dovico/blob/0f1ef2a9be7fe2a9d1ffa73395dcab10fb870e6e/lib/dovico/app.rb#L45

**Comment by paulRbr** [comment]
Patch de mon ancien boss :heart: https://github.com/leejarvis/slop/commit/70e1de88583b934e583aad2b7c2bbffda4a4ea57

**Comment by paulRbr** [comment]
I like your version better for the documentation I'll merge it like this. Thanks!

**Pull request merged**
